import React from 'react';
import Tabs from "react-bootstrap/Tabs";
import Tab from "react-bootstrap/Tab";

function Publication() {

    return (
      <div className="col-12 col-md-10 body">
        <h5>Publications</h5>
        <div className="divider"></div>
        <Tabs defaultActiveKey="journals" id="publication-tab">
          <Tab eventKey="journals" title="Journal">
            <ul className="list-unstyled mt-4 mb-4">
              <p className="publication-item">
                <span>1</span> Ranjeet Rout, Santi P. Maity, Pabitra Pal
                Chowdhury, Jayanta Kumar Das, Sk. Sarif Hassan, Hori Mohan
                Pandey, Analysis of Boolean functions based on Interaction
                graphs and their infuence in System Biology, 32(12), 7803-7821,
                Neural Computing and Applications, Springer, 2020
              </p>
              <p className="publication-item">
                <span>2</span> Abhijit Bhowmik, Gopal Ch. Das, Sanjoy Dhar Ray,
                Sumit Kundu, Santi P. Maity, Allocation of Optimal Energy in an
                Energy-Harvesting Cooperative Multi-band Cognitive Radio
                Network, 26(2), 1033-1043, Wireless Networks, Springer Verlag,
                2020
              </p>
              <p className="publication-item">
                <span>3</span> Avik Banerjee and Santi P. Maity, On Residual
                Energy Maximization in DF Cognitive Radio Networks with Multiple
                Eavesdroppers, 6(2), 718-727, IEEE Transactions on Cognitive
                Communications and Networking, 2020
              </p>
              <p className="publication-item">
                <span>4</span> Srijit Chowdhury, Abderrahim Benslimane and
                Chandan Giri, Non-Cooperative Gaming for Energy Efficient
                Congestion Control in 6LoWPAN, Accepted for Publication in IEEE
                Internet of Things Journal, 2020
              </p>
              <p className="publication-item">
                <span>5</span> Nashreen Nesa and Indrajit Banerjee, Combining
                Merkle Hash Tree and Chaotic Cryptography for Secure Data Fusion
                in IoT, 35, 85--105, Trans. Comput. Sci., 2020
              </p>
              <p className="publication-item">
                <span>6</span> Anal Paul and Santi P. Maity, Outage analysis in cognitive radio networks with energy harvesting and Q-Ruting, 69(6), 6755-6765, IEEE Transactions on Vehicular Technolgy, 2020
              </p>
              <p className="publication-item">
                <span>7</span> S. Kandar, B.C. Dhara, A verifiable secret sharing scheme with combiner verification and cheater identification, 51, Journal of information security and applications, Elsevier, 2020
              </p>
              <p className="publication-item">
                <span>8</span> P.Biswas, S. Kandar, B.C. Dhara, mage encryption using sequence generated by interval bisection of polynomial function, MULTIMEDIA TOOLS AND APPLICATIONS, 2020
              </p>
              <p className="publication-item">
                <span>9</span> Sutanu Ghosh, Tamaghna Acharya, Santi P. Maity, On Outage Analysis in SWIPT Enabled Bidirectional D2D Communications using Spectrum Sharing in Cellular Networks, 10.1109/TVT.2020.3003228, IEEE Transactions on Vehicular Technolgy, 2020
              </p>
              <p className="publication-item">
                <span>10</span> Tapashi Bhattacharjee, Hirak Maity and Santi P. Maity, On FPGA Implementation in SIS with Reversible Watermarking, IET Image Processing (Major revision), 2020
              </p>
              <p className="publication-item">
                <span>11</span> Srijit Chowdhury, Ambarish Roy, Abderrahim Benslimane and Chandan Giri, On Semantic Clustering and Adaptive Robust Regression Based Energy-aware Communication with True Outliers Detection in WSN, Accepetd for publication in Ad Hoc Networks, Elsevier, 2019
              </p>
              <p className="publication-item">
                <span>12</span> Srijit Chowdhury and Chandan Giri, EETC: Energy Eicient Tree-Clustering in Delay Constrained Wireless Sensor Network, Accepted for publication in Wireless Personal Communications, Springer, 2019
              </p>
              <p className="publication-item">
                <span>13</span> Tanusree Kaibartta, Hafizur Rahaman, Chandan Giri and Debesh Das, An Approach of Genetic Algorithm for Power Aware Testing of 3D ICs, IEEE Computer and Digital Techniques, Print ISSN: 1751-8601, Online ISSN: 1751-861X, 2019
              </p>
              <p className="publication-item">
                <span>14</span> Srijit Chowdhury and Chandan Giri, Energy and Network Balanced Distributed Clustering in Wireless Sensor Network, 105(3), 1083–1109, Wireless Personal Communications, Springer US, 2019
              </p>
              <p className="publication-item">
                <span>15</span> L. Banerjee, A Sengupta, and H. Rahaman, Carrier transport and thermoelectric properties of differently shaped Germanene (Ge) and Silicene (Si) nanoribbon interconnects, 66 (1), 664-669, IEEE Transactions on Electron Devices, 2019
              </p>
              <p className="publication-item">
                <span>16</span> Anal Paul and Santi P. Maity, Outage analysis in cognitive radio networks with energy harvesting and Q-Ruting, 69(6), 6755-6765, IEEE Transactions on Vehicular Technolgy, 2020
              </p>
              <p className="publication-item">
                <span>17</span> Dilip Kumar Maity, Surajit Kumar Roy and Chandan Giri, Identification of Random/Clustered TSV Defects in 3D IC during Pre-bond Testing, Accepted for publication in Journal of Electronic Testing:Theory and Applications (JETTA), Springer, 2019
              </p>
              <p className="publication-item">
                <span>18</span> Dhrubasish Sarkar, Sohom Roy, Chandan Giri and Dipka K. Kole, A Statistical Model to Determine the Behavior Adoption in Different Timestamps on Online Social Network, Accepted for publication in International Journal of Knowledge and System Science (IJKSS), IGI Global (Scopus Indexed), 2019 
              </p>
              <p className="publication-item">
                <span>19</span> Oishila Bandyopadhyay and Tapash Dutta and Nilanjan Dutta and Arindam Biswas and Bhargab B. Bhattacharya, Structural feature analysis of the vascular network in retinal images, 7, 37--48, Imaging Visualization, 2019 
              </p>
              <p className="publication-item">
                <span>20</span> Nilanjana Karmakar and Sharmistha Mondal and Arindam Biswas, Determination of 3D curve skeleton of a digital object, 499, 84--101, Inf. Sci., 2019 
              </p>
            </ul>
          </Tab>
          <Tab eventKey="conference" title="Conference">
            <ul className="list-unstyled mt-4 mb-4">
              <p className="publication-item">
                <span>1</span> A.Pal, S.Kandar, B.C.Dhara, Generation of pseudo
                random sequence using Regula-Falsi method, ICMC 2020, Springer,
                2020
              </p>
              <p className="publication-item">
                <span>2</span> Avik Banerje and Santi P. Maity, Cognitive radio
                networks with energy harvesting and eavesdropping-emulation
                resilience, Proc. 12th Int. Conf. on COMSNETS, 2020
              </p>
              <p className="publication-item">
                <span>3</span> Avik Banerjee and Santi P. Maity, PUEA impact on
                sensing and throughput in RF powered cognitive radio networks,
                Proc. 5th Int. Congress on Information and Communication
                Technology (ICICT 2020), London, 19-20th February, 2020, 2020
              </p>
              <p className="publication-item">
                <span>4</span> Tapobrata Dhar, Surajit Kumar Roy and Chandan
                Giri, Hardware Trojan Detection by Stimulating Transitions in
                Rare Nets, Accepted for publication in VLSI Design Conference
                (VLSID)Juanuary, Delhi, India., 2019
              </p>
              <p className="publication-item">
                <span>5</span> Chandrakant Navdeti, Chandan Giri and Indrajit
                Banerjee, Distributed Alpha-Fair Transmit Power Adaptation Based
                Congestion Control in VANET, Accepted for publication in ICDCN
                2019, January 4-7 2019, Bangalore, 2019
              </p>
            </ul>
          </Tab>

          <Tab eventKey="books" title="Books">
            <ul className="list-unstyled mt-4 mb-4">
              <p className="publication-item">
                <span>1</span> A Biswas, P Bhattacharya, S. P. Maity, An
                Efficient Semiautomatic Active Contour Model of Liver Tumor
                Segmentation from CT Images, 75-85, Computational Network
                Application Tools for Performance Management, Springer, 2020
              </p>
              <p className="publication-item">
                <span>2</span> Mihir K Chakraborty, Sukanta Das, Subhasis
                Bandopadhyay, Kamalika Bhattacharjee, Raju Hazari, Sumit Adak,
                Souvik Roy, Supreeti Kamilya, A Journey through the Logic
                Wonderland, Indian Institute of Engineering Science and
                Technology, Shibpur, 2020{" "}
              </p>
              <p className="publication-item">
                <span>3</span> S. Pal, S.Kandar, RSA based Remote User
                Authentication Scheme for Telecare Medical Information System,
                IoT: Privacy and Security paradigm, CRC press Taylor and
                Francis, 2020{" "}
              </p>
              <p className="publication-item">
                <span>4</span> Anal Paul and Santi P. Maity, Differential
                Evolution in PFCM Clustering for Energy Efficient Cooperative
                Spectrum Sensing, 77-101, "Advances in Intelligent Computing”
                Studies of Computational Intelligence, Springer, 2019{" "}
              </p>
              <p className="publication-item">
                <span>5</span> S.Kandar, Undecidability, SLM for M.Sc. Computer
                Sc, DDE, Vidyasagar University, 2019{" "}
              </p>
            </ul>
          </Tab>
        </Tabs>
        <hr />
      </div>
    );
}

export default Publication;